/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "stub.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
date_write_1(data_arg *argp, CLIENT *clnt)
{
	int * clnt_res = (int *)malloc(sizeof(int));

	memset((char *)clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, DATE_WRITE,
		(xdrproc_t) xdr_data_arg, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (clnt_res);
}

data_arg *
date_read_1(data_req *argp, CLIENT *clnt)
{
	data_arg *clnt_res = malloc(sizeof(data_arg));
	
	memset((char *)clnt_res, 0, sizeof(clnt_res));
	
	clnt_res->data.data_len = argp->len;
	if (clnt_call (clnt, DATE_READ,
		(xdrproc_t) xdr_data_req, (caddr_t) argp,
		(xdrproc_t) xdr_data_arg, (caddr_t) clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return clnt_res;
}
