/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "stub.h"

bool_t
xdr_data_arg (XDR *xdrs, data_arg *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_data_req (XDR *xdrs, data_req *objp)
{
	register int32_t *buf;

	 if (!xdr_char (xdrs, &objp->c))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->len))
		 return FALSE;
	return TRUE;
}
