/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "stub.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

pthread_mutex_t mt_mutex;


static void
osdprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		data_arg date_write_1_arg;
		data_req date_read_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case DATE_WRITE:
		_xdr_argument = (xdrproc_t) xdr_data_arg;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) date_write_1_svc;
		break;

	case DATE_READ:
		_xdr_argument = (xdrproc_t) xdr_data_req;
		_xdr_result = (xdrproc_t) xdr_data_arg;
		local = (char *(*)(char *, struct svc_req *)) date_read_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}

	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	free(result);
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	//pmap_unset (OSDPROG, OSDVERS);

	pthread_mutex_init( &mt_mutex, NULL );
	/*if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, OSDPROG, OSDVERS, osdprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (OSDPROG, OSDVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, OSDPROG, OSDVERS, osdprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (OSDPROG, OSDVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);*/

	transp = svcrdma_create();

	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create rdma service.");
		exit(1);
	}
	printf("create rdma transp success~\n");

	if (!svc_register(transp, OSDPROG, OSDVERS, osdprog_1, 37549)) {
		fprintf (stderr, "%s", "unable to register (OSDPROG, OSDVERS, rdma).");
		exit(1);
	}
	printf("reg rdma transp success~\n");

	printf("server is running\n");
	svc_run_rdma ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
